[build]
  command = "npm run build:ssr"
  publish = "dist/WebQuanLyCuaHangSach/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-angular-universal"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev:ssr"
  port = 8080
