[build]
  # Lệnh để xây dựng ứng dụng của bạn
  command = "npm run build"

  # Thư mục chứa các tệp tĩnh để triển khai
  publish = "dist/WebQuanLyCuaHangSach/browser"

[[redirects]]
  # Định tuyến tất cả các yêu cầu đến ứng dụng Angular của bạn
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
