[build]
  command = "npm run build:ssr"
  publish = "dist/WebQuanLyCuaHangSach/browser"
  functions = "dist/WebQuanLyCuaHangSach/server"

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
